### PR TITLE
Fix/activated

### PR DESCRIPTION
**Pull request by Chichilele**
There was no logic around the activation of the users.
This PR implements the following
* block deactivated users from login in
* block deactivated user from reset password
* block deactivated user from forgot password

### CODE REVIEW

**Review by koutsilisk — APPROVED** [review]
Seems on but why do we through a NoResultFound? Isn't it a bit misleading? The user exists but its not activated. Validation error with custom message maybe a better first iteration approach. Next we could implement our own exception classes like UserNotActivated etc.

**Comment by Chichilele** [comment]
Good point. Are we returning the fact that the user is not activated in the json response? Or do we choose to hide the fact that it's deactivated and show as if the user doesn't't exist

**Comment by koutsilisk** [comment]
> Good point. Are we returning the fact that the user is not activated in the json response? Or do we choose to hide the fact that it's deactivated and show as if the user doesn't't exist

My opinion is to show that is deactivated, I don't think we gain something by hiding the user, just confusion maybe. @joaopcartier Any thoughts on that.

**Comment by joaopcartier** [comment]
> > Good point. Are we returning the fact that the user is not activated in the json response? Or do we choose to hide the fact that it's deactivated and show as if the user doesn't't exist
> 
> My opinion is to show that is deactivated, I don't think we gain something by hiding the user, just confusion maybe. @joaopcartier Any thoughts on that.

I think it would be good the user to know that they have an account but it is deactivated

**Comment by Chichilele** [comment]
Will create another story for the errors

**Comment by Chichilele** [comment]
@koutsilisk implement errors returning user deactivated

**Pull request merged**
